import { useEffect, useMemo, useState } from "react";
import { BookOpen, Check, ChevronLeft, CirclePlus, Eye, FilePenLine, GripVertical, LayoutList, Plus, Save, Trash2 } from "lucide-react";
import { Link } from "wouter";
import DashboardLayout, { type DashboardMenuItem } from "@/components/DashboardLayout";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

type StepType = "warmup" | "explain" | "quiz" | "listen" | "recap";
type DraftStep = { stepType: StepType; title: string; body: string; prompt: string; options: string[]; answerIndex: number; explanation: string; audioText: string };
type Draft = { slug: string; title: string; summary: string; skill: "grammar" | "listening" | "reading" | "speaking" | "mixed"; level: string; estimatedMinutes: number; status: "draft" | "published"; steps: DraftStep[] };
const blankStep = (stepType: StepType = "explain"): DraftStep => ({ stepType, title: stepType === "warmup" ? "Khởi động trí nhớ" : stepType === "recap" ? "Chốt lại một điều" : "Tiêu đề bước học", body: "Viết nội dung ngắn, rõ và có bối cảnh TOEIC.", prompt: "", options: stepType === "quiz" || stepType === "listen" ? ["Lựa chọn A", "Lựa chọn B"] : [], answerIndex: 0, explanation: "Giải thích vì sao lựa chọn này phù hợp.", audioText: "" });
const blankDraft = (): Draft => ({ slug: "", title: "", summary: "", skill: "grammar", level: "Foundation", estimatedMinutes: 15, status: "draft", steps: [blankStep("warmup"), blankStep("explain"), blankStep("quiz"), blankStep("recap")] });
const menuItems: DashboardMenuItem[] = [{ icon: LayoutList, label: "Bài học", path: "/admin/lessons" }, { icon: Eye, label: "Xem thư viện", path: "/lessons" }];
function parseOptions(raw: string | null) { try { const value = JSON.parse(raw ?? "[]"); return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; } catch { return []; } }

export default function AdminLessons() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const list = trpc.admin.lessons.list.useQuery(undefined, { enabled: user?.role === "admin" });
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const detail = trpc.admin.lessons.detail.useQuery({ id: selectedId ?? 0 }, { enabled: selectedId !== null && user?.role === "admin" });
  const [draft, setDraft] = useState<Draft>(blankDraft);
  const create = trpc.admin.lessons.create.useMutation({ onSuccess: async result => { await utils.admin.lessons.list.invalidate(); setSelectedId(result?.lesson.id ?? null); toast.success("Đã tạo bài học."); } });
  const update = trpc.admin.lessons.update.useMutation({ onSuccess: async () => { await utils.admin.lessons.list.invalidate(); await utils.admin.lessons.detail.invalidate(); toast.success("Đã lưu bài học."); } });
  const remove = trpc.admin.lessons.delete.useMutation({ onSuccess: async () => { await utils.admin.lessons.list.invalidate(); setSelectedId(null); setDraft(blankDraft()); toast.success("Đã xóa bài học."); } });
  useEffect(() => { const data = detail.data; if (!data) return; setDraft({ slug: data.lesson.slug, title: data.lesson.title, summary: data.lesson.summary, skill: data.lesson.skill, level: data.lesson.level, estimatedMinutes: data.lesson.estimatedMinutes, status: data.lesson.status, steps: data.steps.map(step => ({ stepType: step.stepType, title: step.title, body: step.body, prompt: step.prompt ?? "", options: parseOptions(step.optionsJson), answerIndex: step.answerIndex ?? 0, explanation: step.explanation ?? "", audioText: step.audioText ?? "" })) }); }, [detail.data]);
  const lessonCount = useMemo(() => list.data?.length ?? 0, [list.data]);
  const setField = <K extends keyof Draft>(key: K, value: Draft[K]) => setDraft(previous => ({ ...previous, [key]: value }));
  const updateStep = (index: number, patch: Partial<DraftStep>) => setDraft(previous => ({ ...previous, steps: previous.steps.map((step, position) => position === index ? { ...step, ...patch } : step) }));
  const save = () => { const normalized = { ...draft, slug: draft.slug.trim().toLowerCase(), steps: draft.steps.map(step => ({ ...step, prompt: step.prompt || null, explanation: step.explanation || null, audioText: step.audioText || null, options: step.options.filter(Boolean) })) }; if (selectedId) update.mutate({ id: selectedId, lesson: normalized }); else create.mutate(normalized); };
  return <DashboardLayout menuItems={menuItems} title="Studio nội dung" requireAdmin><div className="admin-lessons">
    <header className="admin-header"><div><span className="eyebrow">OAUTH ADMIN · NỘI DUNG HỌC TẬP</span><h1>Studio bài học</h1><p>Tạo bài giảng đa chặng, lưu nháp trước và chỉ xuất bản khi nội dung đã sẵn sàng.</p></div><div className="admin-header-meta"><strong>{lessonCount}</strong><span>bài học</span></div></header>
    <div className="admin-layout"><aside className="admin-library"><button className="admin-new" onClick={() => { setSelectedId(null); setDraft(blankDraft()); }}><CirclePlus />Bài học mới</button><div className="admin-list">{list.data?.map(lesson => <button className={selectedId === lesson.id ? "selected" : ""} key={lesson.id} onClick={() => setSelectedId(lesson.id)}><span className={lesson.status}>{lesson.status === "published" ? "Đã xuất bản" : "Nháp"}</span><b>{lesson.title}</b><small>{lesson.skill} · {lesson.estimatedMinutes} phút</small></button>)}</div><Link href="/lessons" className="admin-preview-link"><Eye />Xem thư viện học viên</Link></aside>
      <main className="lesson-editor"><div className="editor-top"><div><span className="eyebrow">{selectedId ? "CHỈNH SỬA BÀI HỌC" : "BÀI HỌC MỚI"}</span><h2>{draft.title || "Đặt mục tiêu cho bài học"}</h2></div><div className="editor-actions">{selectedId && <button className="danger" onClick={() => { if (window.confirm("Xóa bài học này cùng các bước và tiến độ liên quan?")) remove.mutate({ id: selectedId }); }}><Trash2 />Xóa</button>}<button className="save" disabled={create.isPending || update.isPending} onClick={save}><Save />{draft.status === "published" ? "Lưu & xuất bản" : "Lưu nháp"}</button></div></div>
        <section className="editor-section editor-basics"><label>Tiêu đề<input value={draft.title} onChange={event => setField("title", event.target.value)} placeholder="Ví dụ: Present Simple trong email công sở" /></label><label>Slug URL<input value={draft.slug} onChange={event => setField("slug", event.target.value)} placeholder="present-simple-email" /></label><label className="span-two">Tóm tắt<textarea value={draft.summary} onChange={event => setField("summary", event.target.value)} placeholder="Người học sẽ hiểu và áp dụng…" /></label><label>Kỹ năng<select value={draft.skill} onChange={event => setField("skill", event.target.value as Draft["skill"])}><option value="grammar">Ngữ pháp</option><option value="listening">Luyện nghe</option><option value="reading">Đọc hiểu</option><option value="speaking">Phát âm</option><option value="mixed">Tổng hợp</option></select></label><label>Cấp độ<input value={draft.level} onChange={event => setField("level", event.target.value)} /></label><label>Thời lượng (phút)<input type="number" min="3" max="90" value={draft.estimatedMinutes} onChange={event => setField("estimatedMinutes", Number(event.target.value))} /></label><label>Trạng thái<select value={draft.status} onChange={event => setField("status", event.target.value as Draft["status"])}><option value="draft">Nháp — chỉ admin thấy</option><option value="published">Xuất bản — học viên thấy</option></select></label></section>
        <section className="editor-steps"><div className="steps-heading"><div><span className="eyebrow">KỊCH BẢN BÀI HỌC</span><h3>{draft.steps.length} bước có dẫn dắt</h3></div><button onClick={() => setDraft(previous => ({ ...previous, steps: [...previous.steps, blankStep("explain")] }))}><Plus />Thêm bước</button></div>{draft.steps.map((step, index) => <article className="step-editor" key={`${step.stepType}-${index}`}><div className="step-editor-head"><span><GripVertical />BƯỚC {index + 1}</span><select value={step.stepType} onChange={event => { const stepType = event.target.value as StepType; updateStep(index, { stepType, options: stepType === "quiz" || stepType === "listen" ? step.options.length ? step.options : ["Lựa chọn A", "Lựa chọn B"] : [] }); }}><option value="warmup">Khởi động</option><option value="explain">Giải thích</option><option value="quiz">Quiz</option><option value="listen">Lắng nghe + quiz</option><option value="recap">Tổng kết</option></select>{draft.steps.length > 1 && <button aria-label="Xóa bước" onClick={() => setDraft(previous => ({ ...previous, steps: previous.steps.filter((_, position) => position !== index) }))}><Trash2 /></button>}</div><label>Tiêu đề<input value={step.title} onChange={event => updateStep(index, { title: event.target.value })} /></label><label>Nội dung<textarea value={step.body} onChange={event => updateStep(index, { body: event.target.value })} /></label><label>Gợi ý / câu hỏi (tùy chọn)<textarea value={step.prompt} onChange={event => updateStep(index, { prompt: event.target.value })} /></label>{step.stepType === "listen" && <label>Đoạn audio tổng hợp<textarea value={step.audioText} onChange={event => updateStep(index, { audioText: event.target.value })} placeholder="Nhập câu hoặc đoạn ngắn để người học nghe." /></label>}{(step.stepType === "quiz" || step.stepType === "listen") && <div className="quiz-fields"><label>Lựa chọn (mỗi dòng một đáp án)<textarea value={step.options.join("\n")} onChange={event => updateStep(index, { options: event.target.value.split("\n") })} /></label><label>Đáp án đúng<select value={step.answerIndex} onChange={event => updateStep(index, { answerIndex: Number(event.target.value) })}>{step.options.filter(Boolean).map((option, optionIndex) => <option key={`${option}-${optionIndex}`} value={optionIndex}>{String.fromCharCode(65 + optionIndex)} · {option}</option>)}</select></label><label>Giải thích sau khi trả lời<textarea value={step.explanation} onChange={event => updateStep(index, { explanation: event.target.value })} /></label></div>}</article>)}</section>
      </main></div>
  </div></DashboardLayout>;
}
