export type BusinessPracticeQuestion = {
  id: string;
  part: 3 | 7;
  skill: "listening" | "reading";
  contextLabel: string;
  prompt: string;
  choices: [string, string, string, string];
  answer: number;
  transcript?: string;
  passage?: string;
  explanation: string;
};

export type BusinessPracticeSet = {
  id: string;
  title: string;
  summary: string;
  estimatedMinutes: number;
  tags: string[];
  questions: BusinessPracticeQuestion[];
};

const q = (question: BusinessPracticeQuestion) => question;

export const businessPracticeSets: BusinessPracticeSet[] = [
  {
    id: "project-launch-vendor",
    title: "Khởi động dự án & phối hợp nhà cung cấp",
    summary: "Luyện nghe cập nhật tiến độ và đọc email–bảng giao hàng trong tuần ra mắt sản phẩm.",
    estimatedMinutes: 15,
    tags: ["project launch", "vendor", "delivery"],
    questions: [
      q({ id: "plv-p3-01", part: 3, skill: "listening", contextLabel: "Part 3 · Project launch call", transcript: "Woman: Hi Daniel, I am checking on the product launch display. Has BrightLine sent the revised artwork? Man: Yes, they sent it yesterday afternoon. I asked our design team to approve the color proof by noon tomorrow. Woman: Good. Once that is done, I will confirm the installation time with the mall manager.", prompt: "What are the speakers mainly discussing?", choices: ["A product display for an upcoming launch.", "A change to an employee handbook.", "A request for a new office lease.", "A plan to interview designers."], answer: 0, explanation: "Họ nhắc đến product launch display, revised artwork và installation time, nên chủ đề là trưng bày cho lễ ra mắt." }),
      q({ id: "plv-p3-02", part: 3, skill: "listening", contextLabel: "Part 3 · Project launch call", transcript: "Woman: Hi Daniel, I am checking on the product launch display. Has BrightLine sent the revised artwork? Man: Yes, they sent it yesterday afternoon. I asked our design team to approve the color proof by noon tomorrow. Woman: Good. Once that is done, I will confirm the installation time with the mall manager.", prompt: "What will the design team do?", choices: ["Approve a color proof.", "Install the display.", "Meet the mall manager.", "Send a price quotation."], answer: 0, explanation: "Daniel nói rõ đã yêu cầu design team approve the color proof by noon tomorrow." }),
      q({ id: "plv-p3-03", part: 3, skill: "listening", contextLabel: "Part 3 · Project launch call", transcript: "Woman: Hi Daniel, I am checking on the product launch display. Has BrightLine sent the revised artwork? Man: Yes, they sent it yesterday afternoon. I asked our design team to approve the color proof by noon tomorrow. Woman: Good. Once that is done, I will confirm the installation time with the mall manager.", prompt: "What will the woman most likely do next?", choices: ["Confirm an installation time.", "Revise the artwork herself.", "Hire a new design team.", "Move the product launch."], answer: 0, explanation: "Sau khi color proof được duyệt, cô ấy nói sẽ confirm installation time với mall manager." }),
      q({ id: "plv-p3-04", part: 3, skill: "listening", contextLabel: "Part 3 · Delivery coordination", transcript: "Man: Ms. Patel, the cartons for the Westside store arrived at our warehouse, but the labels list Thursday as the delivery date. Woman: That is later than we requested. The store is hosting a preview event on Wednesday evening. Man: I will call the carrier. If they cannot deliver early, we can use our local courier for the final trip.", prompt: "What problem does the man mention?", choices: ["The delivery is scheduled too late.", "The cartons were sent to the wrong warehouse.", "The store cancelled its event.", "The labels are missing product names."], answer: 0, explanation: "Nhãn ghi Thursday, trong khi preview event diễn ra Wednesday evening; vì vậy lịch giao quá muộn." }),
      q({ id: "plv-p3-05", part: 3, skill: "listening", contextLabel: "Part 3 · Delivery coordination", transcript: "Man: Ms. Patel, the cartons for the Westside store arrived at our warehouse, but the labels list Thursday as the delivery date. Woman: That is later than we requested. The store is hosting a preview event on Wednesday evening. Man: I will call the carrier. If they cannot deliver early, we can use our local courier for the final trip.", prompt: "Why does the woman need the cartons earlier?", choices: ["A preview event is planned.", "A supplier is visiting the store.", "The warehouse will close for repairs.", "The labels must be redesigned."], answer: 0, explanation: "Cô ấy giải thích store is hosting a preview event on Wednesday evening." }),
      q({ id: "plv-p3-06", part: 3, skill: "listening", contextLabel: "Part 3 · Delivery coordination", transcript: "Man: Ms. Patel, the cartons for the Westside store arrived at our warehouse, but the labels list Thursday as the delivery date. Woman: That is later than we requested. The store is hosting a preview event on Wednesday evening. Man: I will call the carrier. If they cannot deliver early, we can use our local courier for the final trip.", prompt: "What alternative does the man propose?", choices: ["Using a local courier.", "Rescheduling the preview event.", "Shipping cartons from another country.", "Returning the cartons to the vendor."], answer: 0, explanation: "Nếu carrier không giao sớm, anh ấy đề xuất local courier cho chặng cuối." }),
      q({ id: "plv-p7-01", part: 7, skill: "reading", contextLabel: "Part 7 · Launch email and delivery schedule", passage: "EMAIL\nTo: Launch Team\nFrom: M. Chen, Operations\nSubject: Harborview launch materials\n\nThe Harborview Hotel has confirmed that the lobby display may be installed after 6 P.M. on Tuesday, May 14. Please send the final artwork approval to BrightLine by 11 A.M. Monday so that its crew can prepare the panels.\n\nDELIVERY SCHEDULE\nMonday 9:00 A.M. — BrightLine collects approved artwork\nTuesday 2:00 P.M. — Materials arrive at Harborview loading dock\nTuesday 6:30 P.M. — Installation begins\nWednesday 8:00 A.M. — Team inspection", prompt: "Why was the email written?", choices: ["To communicate launch-material deadlines and logistics.", "To invite staff to a hotel conference.", "To request a new display design.", "To announce a change in company policy."], answer: 0, explanation: "Email nêu thời hạn artwork và thời gian giao/lắp vật liệu cho launch." }),
      q({ id: "plv-p7-02", part: 7, skill: "reading", contextLabel: "Part 7 · Launch email and delivery schedule", passage: "EMAIL\nTo: Launch Team\nFrom: M. Chen, Operations\nSubject: Harborview launch materials\n\nThe Harborview Hotel has confirmed that the lobby display may be installed after 6 P.M. on Tuesday, May 14. Please send the final artwork approval to BrightLine by 11 A.M. Monday so that its crew can prepare the panels.\n\nDELIVERY SCHEDULE\nMonday 9:00 A.M. — BrightLine collects approved artwork\nTuesday 2:00 P.M. — Materials arrive at Harborview loading dock\nTuesday 6:30 P.M. — Installation begins\nWednesday 8:00 A.M. — Team inspection", prompt: "What must happen by 11 A.M. Monday?", choices: ["The final artwork must be approved.", "The panels must be installed.", "The team must inspect the display.", "The hotel must receive materials."], answer: 0, explanation: "M. Chen yêu cầu send the final artwork approval by 11 A.M. Monday." }),
      q({ id: "plv-p7-03", part: 7, skill: "reading", contextLabel: "Part 7 · Launch email and delivery schedule", passage: "EMAIL\nTo: Launch Team\nFrom: M. Chen, Operations\nSubject: Harborview launch materials\n\nThe Harborview Hotel has confirmed that the lobby display may be installed after 6 P.M. on Tuesday, May 14. Please send the final artwork approval to BrightLine by 11 A.M. Monday so that its crew can prepare the panels.\n\nDELIVERY SCHEDULE\nMonday 9:00 A.M. — BrightLine collects approved artwork\nTuesday 2:00 P.M. — Materials arrive at Harborview loading dock\nTuesday 6:30 P.M. — Installation begins\nWednesday 8:00 A.M. — Team inspection", prompt: "When will the materials arrive at the hotel?", choices: ["Tuesday afternoon.", "Monday morning.", "Tuesday evening.", "Wednesday morning."], answer: 0, explanation: "Delivery schedule ghi Tuesday 2:00 P.M. at Harborview loading dock." }),
      q({ id: "plv-p7-04", part: 7, skill: "reading", contextLabel: "Part 7 · Launch email and delivery schedule", passage: "EMAIL\nTo: Launch Team\nFrom: M. Chen, Operations\nSubject: Harborview launch materials\n\nThe Harborview Hotel has confirmed that the lobby display may be installed after 6 P.M. on Tuesday, May 14. Please send the final artwork approval to BrightLine by 11 A.M. Monday so that its crew can prepare the panels.\n\nDELIVERY SCHEDULE\nMonday 9:00 A.M. — BrightLine collects approved artwork\nTuesday 2:00 P.M. — Materials arrive at Harborview loading dock\nTuesday 6:30 P.M. — Installation begins\nWednesday 8:00 A.M. — Team inspection", prompt: "What is suggested about BrightLine?", choices: ["It will prepare the display panels.", "It manages the hotel lobby.", "It will conduct the team inspection.", "It printed the delivery schedule."], answer: 0, explanation: "Email nói BrightLine's crew can prepare the panels after receiving approval." }),
      q({ id: "plv-p7-05", part: 7, skill: "reading", contextLabel: "Part 7 · Launch email and delivery schedule", passage: "EMAIL\nTo: Launch Team\nFrom: M. Chen, Operations\nSubject: Harborview launch materials\n\nThe Harborview Hotel has confirmed that the lobby display may be installed after 6 P.M. on Tuesday, May 14. Please send the final artwork approval to BrightLine by 11 A.M. Monday so that its crew can prepare the panels.\n\nDELIVERY SCHEDULE\nMonday 9:00 A.M. — BrightLine collects approved artwork\nTuesday 2:00 P.M. — Materials arrive at Harborview loading dock\nTuesday 6:30 P.M. — Installation begins\nWednesday 8:00 A.M. — Team inspection", prompt: "What will occur immediately before installation begins?", choices: ["The materials will be delivered.", "The artwork will be collected.", "The team will inspect the display.", "The hotel will confirm the lobby."], answer: 0, explanation: "Materials arrive Tuesday 2 P.M., then installation begins Tuesday 6:30 P.M." }),
      q({ id: "plv-p7-06", part: 7, skill: "reading", contextLabel: "Part 7 · Launch email and delivery schedule", passage: "EMAIL\nTo: Launch Team\nFrom: M. Chen, Operations\nSubject: Harborview launch materials\n\nThe Harborview Hotel has confirmed that the lobby display may be installed after 6 P.M. on Tuesday, May 14. Please send the final artwork approval to BrightLine by 11 A.M. Monday so that its crew can prepare the panels.\n\nDELIVERY SCHEDULE\nMonday 9:00 A.M. — BrightLine collects approved artwork\nTuesday 2:00 P.M. — Materials arrive at Harborview loading dock\nTuesday 6:30 P.M. — Installation begins\nWednesday 8:00 A.M. — Team inspection", prompt: "The word “final” in the email is closest in meaning to", choices: ["last and complete", "temporary", "unnecessary", "inexpensive"], answer: 0, explanation: "Final artwork approval là bản phê duyệt cuối cùng, hoàn chỉnh trước khi sản xuất/lắp đặt." }),
    ],
  },
  {
    id: "account-service-recovery",
    title: "Quản lý tài khoản & xử lý dịch vụ khách hàng",
    summary: "Rèn phản xạ với cuộc gọi gia hạn hợp đồng, xử lý hóa đơn và email theo dõi khách hàng doanh nghiệp.",
    estimatedMinutes: 15,
    tags: ["account management", "invoice", "customer service"],
    questions: [
      q({ id: "asr-p3-01", part: 3, skill: "listening", contextLabel: "Part 3 · Account renewal", transcript: "Woman: Mr. Ortiz, I noticed that your maintenance agreement expires at the end of this month. Would you like me to send a renewal proposal? Man: Please do, but include the remote-monitoring option. Our regional offices have expanded since last year. Woman: Certainly. I will send two pricing plans before our call on Friday.", prompt: "Why does the woman call the man?", choices: ["To discuss renewing an agreement.", "To schedule equipment delivery.", "To report a software outage.", "To arrange a job interview."], answer: 0, explanation: "Cô ấy nhắc maintenance agreement expires và đề nghị gửi renewal proposal." }),
      q({ id: "asr-p3-02", part: 3, skill: "listening", contextLabel: "Part 3 · Account renewal", transcript: "Woman: Mr. Ortiz, I noticed that your maintenance agreement expires at the end of this month. Would you like me to send a renewal proposal? Man: Please do, but include the remote-monitoring option. Our regional offices have expanded since last year. Woman: Certainly. I will send two pricing plans before our call on Friday.", prompt: "What does the man request?", choices: ["An option for remote monitoring.", "A later expiration date.", "A technician visit this month.", "A reduction in office space."], answer: 0, explanation: "Anh ấy yêu cầu include the remote-monitoring option." }),
      q({ id: "asr-p3-03", part: 3, skill: "listening", contextLabel: "Part 3 · Account renewal", transcript: "Woman: Mr. Ortiz, I noticed that your maintenance agreement expires at the end of this month. Would you like me to send a renewal proposal? Man: Please do, but include the remote-monitoring option. Our regional offices have expanded since last year. Woman: Certainly. I will send two pricing plans before our call on Friday.", prompt: "What will the woman do before Friday?", choices: ["Send two pricing plans.", "Visit regional offices.", "Install remote monitors.", "Cancel the agreement."], answer: 0, explanation: "Cô ấy khẳng định sẽ send two pricing plans before their call on Friday." }),
      q({ id: "asr-p3-04", part: 3, skill: "listening", contextLabel: "Part 3 · Invoice inquiry", transcript: "Man: Hello, this is Kai from Northwind Supplies. We received an invoice that includes a rush-shipping fee. Woman: Let me check the order record. I see that the delivery date was changed after the purchase order was approved. Man: I understand. Could you send the approval note to our finance team? Woman: Of course. I will attach it to my reply this afternoon.", prompt: "What concern does the man have?", choices: ["An additional delivery charge.", "A missing purchase order.", "A delayed product return.", "An incorrect payment address."], answer: 0, explanation: "Anh ấy hỏi về invoice có rush-shipping fee." }),
      q({ id: "asr-p3-05", part: 3, skill: "listening", contextLabel: "Part 3 · Invoice inquiry", transcript: "Man: Hello, this is Kai from Northwind Supplies. We received an invoice that includes a rush-shipping fee. Woman: Let me check the order record. I see that the delivery date was changed after the purchase order was approved. Man: I understand. Could you send the approval note to our finance team? Woman: Of course. I will attach it to my reply this afternoon.", prompt: "What caused the extra charge?", choices: ["A delivery date was changed.", "The order was returned.", "The product price increased.", "The invoice was paid late."], answer: 0, explanation: "Order record shows delivery date was changed after approval, dẫn đến rush shipping." }),
      q({ id: "asr-p3-06", part: 3, skill: "listening", contextLabel: "Part 3 · Invoice inquiry", transcript: "Man: Hello, this is Kai from Northwind Supplies. We received an invoice that includes a rush-shipping fee. Woman: Let me check the order record. I see that the delivery date was changed after the purchase order was approved. Man: I understand. Could you send the approval note to our finance team? Woman: Of course. I will attach it to my reply this afternoon.", prompt: "What will the woman most likely send?", choices: ["An approval note.", "A revised purchase order.", "A refund form.", "A shipment tracking number."], answer: 0, explanation: "Cô ấy nói sẽ attach the approval note to her reply." }),
      q({ id: "asr-p7-01", part: 7, skill: "reading", contextLabel: "Part 7 · Client email and service notice", passage: "EMAIL\nTo: Account Services\nFrom: L. Morgan, Alder & Co.\nSubject: Saturday platform maintenance\n\nOur sales team processes orders on Saturday mornings. Could you confirm whether the scheduled maintenance will affect reporting tools as well as the customer portal? If so, we will notify staff today.\n\nSERVICE NOTICE\nSaturday, June 8, 1:00–4:00 A.M.\nThe customer portal will be unavailable while security updates are installed. Reporting tools will remain available. No action is required from users after service is restored.", prompt: "Why did L. Morgan write the email?", choices: ["To ask about the effects of scheduled maintenance.", "To request a security update.", "To report a missing customer order.", "To cancel a Saturday meeting."], answer: 0, explanation: "Email asks whether maintenance affects reporting tools and customer portal." }),
      q({ id: "asr-p7-02", part: 7, skill: "reading", contextLabel: "Part 7 · Client email and service notice", passage: "EMAIL\nTo: Account Services\nFrom: L. Morgan, Alder & Co.\nSubject: Saturday platform maintenance\n\nOur sales team processes orders on Saturday mornings. Could you confirm whether the scheduled maintenance will affect reporting tools as well as the customer portal? If so, we will notify staff today.\n\nSERVICE NOTICE\nSaturday, June 8, 1:00–4:00 A.M.\nThe customer portal will be unavailable while security updates are installed. Reporting tools will remain available. No action is required from users after service is restored.", prompt: "What does the notice indicate about reporting tools?", choices: ["They will remain available.", "They require a security update.", "They will be replaced on Saturday.", "They are used only by customers."], answer: 0, explanation: "Service notice states explicitly: Reporting tools will remain available." }),
      q({ id: "asr-p7-03", part: 7, skill: "reading", contextLabel: "Part 7 · Client email and service notice", passage: "EMAIL\nTo: Account Services\nFrom: L. Morgan, Alder & Co.\nSubject: Saturday platform maintenance\n\nOur sales team processes orders on Saturday mornings. Could you confirm whether the scheduled maintenance will affect reporting tools as well as the customer portal? If so, we will notify staff today.\n\nSERVICE NOTICE\nSaturday, June 8, 1:00–4:00 A.M.\nThe customer portal will be unavailable while security updates are installed. Reporting tools will remain available. No action is required from users after service is restored.", prompt: "When will the customer portal be unavailable?", choices: ["Early Saturday morning.", "Saturday afternoon.", "Friday evening.", "All weekend."], answer: 0, explanation: "Notice gives Saturday 1:00–4:00 A.M., tức sáng sớm thứ Bảy." }),
      q({ id: "asr-p7-04", part: 7, skill: "reading", contextLabel: "Part 7 · Client email and service notice", passage: "EMAIL\nTo: Account Services\nFrom: L. Morgan, Alder & Co.\nSubject: Saturday platform maintenance\n\nOur sales team processes orders on Saturday mornings. Could you confirm whether the scheduled maintenance will affect reporting tools as well as the customer portal? If so, we will notify staff today.\n\nSERVICE NOTICE\nSaturday, June 8, 1:00–4:00 A.M.\nThe customer portal will be unavailable while security updates are installed. Reporting tools will remain available. No action is required from users after service is restored.", prompt: "What is suggested about Alder & Co.?", choices: ["Its sales team uses the platform on Saturdays.", "It develops the reporting tools.", "It is installing security updates.", "It has no customer portal."], answer: 0, explanation: "L. Morgan says their sales team processes orders on Saturday mornings." }),
      q({ id: "asr-p7-05", part: 7, skill: "reading", contextLabel: "Part 7 · Client email and service notice", passage: "EMAIL\nTo: Account Services\nFrom: L. Morgan, Alder & Co.\nSubject: Saturday platform maintenance\n\nOur sales team processes orders on Saturday mornings. Could you confirm whether the scheduled maintenance will affect reporting tools as well as the customer portal? If so, we will notify staff today.\n\nSERVICE NOTICE\nSaturday, June 8, 1:00–4:00 A.M.\nThe customer portal will be unavailable while security updates are installed. Reporting tools will remain available. No action is required from users after service is restored.", prompt: "What will users need to do after the service is restored?", choices: ["Nothing.", "Reset their passwords.", "Download a report.", "Contact Account Services."], answer: 0, explanation: "Notice says No action is required from users after service is restored." }),
      q({ id: "asr-p7-06", part: 7, skill: "reading", contextLabel: "Part 7 · Client email and service notice", passage: "EMAIL\nTo: Account Services\nFrom: L. Morgan, Alder & Co.\nSubject: Saturday platform maintenance\n\nOur sales team processes orders on Saturday mornings. Could you confirm whether the scheduled maintenance will affect reporting tools as well as the customer portal? If so, we will notify staff today.\n\nSERVICE NOTICE\nSaturday, June 8, 1:00–4:00 A.M.\nThe customer portal will be unavailable while security updates are installed. Reporting tools will remain available. No action is required from users after service is restored.", prompt: "The word “scheduled” in the email is closest in meaning to", choices: ["planned", "delayed", "unexpected", "unnecessary"], answer: 0, explanation: "Scheduled maintenance nghĩa là bảo trì đã được lên lịch/planned." }),
    ],
  },
  {
    id: "talent-workplace-operations",
    title: "Nhân sự & vận hành nơi làm việc",
    summary: "Thực hành các tình huống tuyển dụng, onboarding, không gian làm việc và thông báo nội bộ có nhiều chi tiết.",
    estimatedMinutes: 15,
    tags: ["recruitment", "onboarding", "workplace"],
    questions: [
      q({ id: "two-p3-01", part: 3, skill: "listening", contextLabel: "Part 3 · New-hire onboarding", transcript: "Man: Priya, the new analysts begin next Monday. Have their laptop requests been completed? Woman: The equipment is ready, but the building-access cards will not arrive until Tuesday. Man: In that case, I will reserve the training room for the first day and ask the team to work there together. Woman: That will work. I will update the welcome schedule.", prompt: "What is the problem?", choices: ["Access cards will arrive late.", "The analysts declined the offer.", "The training room is unavailable.", "The laptop requests were cancelled."], answer: 0, explanation: "Woman says building-access cards will not arrive until Tuesday, sau ngày bắt đầu Monday." }),
      q({ id: "two-p3-02", part: 3, skill: "listening", contextLabel: "Part 3 · New-hire onboarding", transcript: "Man: Priya, the new analysts begin next Monday. Have their laptop requests been completed? Woman: The equipment is ready, but the building-access cards will not arrive until Tuesday. Man: In that case, I will reserve the training room for the first day and ask the team to work there together. Woman: That will work. I will update the welcome schedule.", prompt: "What will the man do?", choices: ["Reserve a training room.", "Order more laptops.", "Issue access cards.", "Interview new analysts."], answer: 0, explanation: "He says he will reserve the training room for the first day." }),
      q({ id: "two-p3-03", part: 3, skill: "listening", contextLabel: "Part 3 · New-hire onboarding", transcript: "Man: Priya, the new analysts begin next Monday. Have their laptop requests been completed? Woman: The equipment is ready, but the building-access cards will not arrive until Tuesday. Man: In that case, I will reserve the training room for the first day and ask the team to work there together. Woman: That will work. I will update the welcome schedule.", prompt: "What will the woman most likely do next?", choices: ["Revise a schedule.", "Prepare equipment.", "Send access cards.", "Meet job candidates."], answer: 0, explanation: "She says she will update the welcome schedule." }),
      q({ id: "two-p3-04", part: 3, skill: "listening", contextLabel: "Part 3 · Office services", transcript: "Woman: The fifth-floor meeting room is booked for the client workshop, but its video screen is being replaced. Man: The replacement should be finished by Thursday morning. Is the workshop later that day? Woman: It starts at two. I will still ask Facilities to test the connection at noon, just in case. Man: Good idea. I will add that to the service request.", prompt: "Why is the woman concerned about the meeting room?", choices: ["Its video screen is being replaced.", "It has been booked by another client.", "Its connection is too slow.", "It is on the wrong floor."], answer: 0, explanation: "Workshop room's video screen is being replaced." }),
      q({ id: "two-p3-05", part: 3, skill: "listening", contextLabel: "Part 3 · Office services", transcript: "Woman: The fifth-floor meeting room is booked for the client workshop, but its video screen is being replaced. Man: The replacement should be finished by Thursday morning. Is the workshop later that day? Woman: It starts at two. I will still ask Facilities to test the connection at noon, just in case. Man: Good idea. I will add that to the service request.", prompt: "When will the workshop begin?", choices: ["Thursday afternoon.", "Thursday morning.", "Wednesday afternoon.", "Friday morning."], answer: 0, explanation: "She says it starts at two after he references Thursday." }),
      q({ id: "two-p3-06", part: 3, skill: "listening", contextLabel: "Part 3 · Office services", transcript: "Woman: The fifth-floor meeting room is booked for the client workshop, but its video screen is being replaced. Man: The replacement should be finished by Thursday morning. Is the workshop later that day? Woman: It starts at two. I will still ask Facilities to test the connection at noon, just in case. Man: Good idea. I will add that to the service request.", prompt: "What will the man add to a service request?", choices: ["A connection test.", "A room reservation.", "A new video screen.", "A client invitation."], answer: 0, explanation: "He agrees to add the Facilities connection test to the service request." }),
      q({ id: "two-p7-01", part: 7, skill: "reading", contextLabel: "Part 7 · Onboarding memo and timetable", passage: "MEMO\nTo: New employees\nFrom: People Operations\n\nWelcome to Greystone Consulting. Your first-day orientation begins at 9:30 A.M. in Room 4B. Please bring government-issued identification so that security can create your building-access card. Laptops will be distributed after lunch.\n\nORIENTATION TIMETABLE\n9:30 A.M. — Welcome and benefits overview\n11:00 A.M. — Security identification check\n12:15 P.M. — Lunch with department leads\n1:30 P.M. — Laptop distribution\n3:00 P.M. — Systems introduction", prompt: "What is the purpose of the memo?", choices: ["To provide first-day instructions.", "To announce an open position.", "To explain a change in benefits.", "To request laptop repairs."], answer: 0, explanation: "Memo welcomes new employees and gives orientation instructions and schedule." }),
      q({ id: "two-p7-02", part: 7, skill: "reading", contextLabel: "Part 7 · Onboarding memo and timetable", passage: "MEMO\nTo: New employees\nFrom: People Operations\n\nWelcome to Greystone Consulting. Your first-day orientation begins at 9:30 A.M. in Room 4B. Please bring government-issued identification so that security can create your building-access card. Laptops will be distributed after lunch.\n\nORIENTATION TIMETABLE\n9:30 A.M. — Welcome and benefits overview\n11:00 A.M. — Security identification check\n12:15 P.M. — Lunch with department leads\n1:30 P.M. — Laptop distribution\n3:00 P.M. — Systems introduction", prompt: "What should new employees bring?", choices: ["Government-issued identification.", "A personal laptop.", "A benefits application.", "A department schedule."], answer: 0, explanation: "Memo specifically asks for government-issued identification for access cards." }),
      q({ id: "two-p7-03", part: 7, skill: "reading", contextLabel: "Part 7 · Onboarding memo and timetable", passage: "MEMO\nTo: New employees\nFrom: People Operations\n\nWelcome to Greystone Consulting. Your first-day orientation begins at 9:30 A.M. in Room 4B. Please bring government-issued identification so that security can create your building-access card. Laptops will be distributed after lunch.\n\nORIENTATION TIMETABLE\n9:30 A.M. — Welcome and benefits overview\n11:00 A.M. — Security identification check\n12:15 P.M. — Lunch with department leads\n1:30 P.M. — Laptop distribution\n3:00 P.M. — Systems introduction", prompt: "When will the employees receive laptops?", choices: ["At 1:30 P.M.", "At 9:30 A.M.", "At 11:00 A.M.", "At 3:00 P.M."], answer: 0, explanation: "Timetable lists Laptop distribution at 1:30 P.M." }),
      q({ id: "two-p7-04", part: 7, skill: "reading", contextLabel: "Part 7 · Onboarding memo and timetable", passage: "MEMO\nTo: New employees\nFrom: People Operations\n\nWelcome to Greystone Consulting. Your first-day orientation begins at 9:30 A.M. in Room 4B. Please bring government-issued identification so that security can create your building-access card. Laptops will be distributed after lunch.\n\nORIENTATION TIMETABLE\n9:30 A.M. — Welcome and benefits overview\n11:00 A.M. — Security identification check\n12:15 P.M. — Lunch with department leads\n1:30 P.M. — Laptop distribution\n3:00 P.M. — Systems introduction", prompt: "What will happen immediately before lunch?", choices: ["A security identification check.", "A benefits overview.", "Laptop distribution.", "A systems introduction."], answer: 0, explanation: "The 11:00 A.M. security check is immediately before 12:15 lunch." }),
      q({ id: "two-p7-05", part: 7, skill: "reading", contextLabel: "Part 7 · Onboarding memo and timetable", passage: "MEMO\nTo: New employees\nFrom: People Operations\n\nWelcome to Greystone Consulting. Your first-day orientation begins at 9:30 A.M. in Room 4B. Please bring government-issued identification so that security can create your building-access card. Laptops will be distributed after lunch.\n\nORIENTATION TIMETABLE\n9:30 A.M. — Welcome and benefits overview\n11:00 A.M. — Security identification check\n12:15 P.M. — Lunch with department leads\n1:30 P.M. — Laptop distribution\n3:00 P.M. — Systems introduction", prompt: "What is suggested about Room 4B?", choices: ["It is the orientation location.", "It is a security office.", "It is where lunches are served.", "It contains the laptop inventory."], answer: 0, explanation: "Memo says first-day orientation begins in Room 4B." }),
      q({ id: "two-p7-06", part: 7, skill: "reading", contextLabel: "Part 7 · Onboarding memo and timetable", passage: "MEMO\nTo: New employees\nFrom: People Operations\n\nWelcome to Greystone Consulting. Your first-day orientation begins at 9:30 A.M. in Room 4B. Please bring government-issued identification so that security can create your building-access card. Laptops will be distributed after lunch.\n\nORIENTATION TIMETABLE\n9:30 A.M. — Welcome and benefits overview\n11:00 A.M. — Security identification check\n12:15 P.M. — Lunch with department leads\n1:30 P.M. — Laptop distribution\n3:00 P.M. — Systems introduction", prompt: "The word “distributed” is closest in meaning to", choices: ["given out", "repaired", "collected", "ordered"], answer: 0, explanation: "Laptops will be distributed means they will be given out to employees." }),
    ],
  },
];

export function getBusinessPracticeSet(setId: string) {
  return businessPracticeSets.find(set => set.id === setId);
}
