export type MockQuestion = {
  id: string;
  part: 1 | 2 | 3 | 4 | 5 | 6 | 7;
  skill: "listening" | "reading";
  prompt: string;
  choices: string[];
  answer: number;
  transcript?: string;
  passage?: string;
  contextLabel: string;
};

export const mockQuestions: MockQuestion[] = [
  { id: "p1-1", part: 1, skill: "listening", contextLabel: "Part 1 · Photograph", prompt: "Chọn câu mô tả đúng hình minh họa: một nhân viên đang xếp hồ sơ lên kệ.", transcript: "A woman is placing files on a shelf.", choices: ["A woman is placing files on a shelf.", "A woman is opening a window.", "Several customers are waiting outside.", "The shelves are being repaired."], answer: 0 },
  { id: "p1-2", part: 1, skill: "listening", contextLabel: "Part 1 · Photograph", prompt: "Chọn câu mô tả đúng hình minh họa: hai người đang ngồi đối diện trong phòng họp.", transcript: "Two people are seated across from each other at a table.", choices: ["Two people are standing near an elevator.", "Two people are seated across from each other at a table.", "A meeting room is being cleaned.", "A man is hanging a sign."], answer: 1 },
  { id: "p1-3", part: 1, skill: "listening", contextLabel: "Part 1 · Photograph", prompt: "Chọn câu mô tả đúng hình minh họa: một xe tải ở trước cửa kho.", transcript: "A truck has stopped in front of a warehouse.", choices: ["A truck is being loaded at a warehouse.", "A truck has stopped in front of a warehouse.", "Workers are painting a vehicle.", "Boxes have been placed on a desk."], answer: 1 },
  { id: "p2-1", part: 2, skill: "listening", contextLabel: "Part 2 · Question–Response", prompt: "Nghe câu hỏi và chọn phản hồi phù hợp.", transcript: "Where should I submit the expense report?", choices: ["At the end of the month.", "To the finance department.", "It was approved yesterday.", "For the business trip."], answer: 1 },
  { id: "p2-2", part: 2, skill: "listening", contextLabel: "Part 2 · Question–Response", prompt: "Nghe câu hỏi và chọn phản hồi phù hợp.", transcript: "Has the conference room been reserved?", choices: ["Yes, for three o'clock.", "On the second floor.", "The reservation form.", "I will attend the conference."], answer: 0 },
  { id: "p2-3", part: 2, skill: "listening", contextLabel: "Part 2 · Question–Response", prompt: "Nghe câu hỏi và chọn phản hồi phù hợp.", transcript: "Why was the shipment delayed?", choices: ["By next Wednesday.", "At the loading dock.", "Because of severe weather.", "The shipping label."], answer: 2 },
  { id: "p3-1", part: 3, skill: "listening", contextLabel: "Part 3 · Conversation", prompt: "Nghe hội thoại. Vấn đề chính là gì?", transcript: "Woman: The client meeting was moved to Friday. Man: Then I will update the presentation before Thursday afternoon.", choices: ["Buổi họp bị hủy.", "Buổi họp được dời lịch.", "Bản trình bày đã hoàn thành.", "Khách hàng đổi văn phòng."], answer: 1 },
  { id: "p3-2", part: 3, skill: "listening", contextLabel: "Part 3 · Conversation", prompt: "Nghe hội thoại. Người nam sẽ làm gì?", transcript: "Woman: The client meeting was moved to Friday. Man: Then I will update the presentation before Thursday afternoon.", choices: ["Gọi cho khách hàng.", "Cập nhật bản trình bày.", "Đặt phòng họp.", "In hóa đơn."], answer: 1 },
  { id: "p3-3", part: 3, skill: "listening", contextLabel: "Part 3 · Conversation", prompt: "Nghe hội thoại. Khi nào công việc sẽ hoàn thành?", transcript: "Woman: The client meeting was moved to Friday. Man: Then I will update the presentation before Thursday afternoon.", choices: ["Thứ Sáu", "Trước chiều thứ Năm", "Cuối tháng", "Ngay hôm nay"], answer: 1 },
  { id: "p4-1", part: 4, skill: "listening", contextLabel: "Part 4 · Talk", prompt: "Nghe thông báo. Thông báo dành cho ai?", transcript: "Attention passengers: Flight 318 to Singapore will depart from Gate 12, not Gate 8. Boarding begins at 6:40 p.m.", choices: ["Nhân viên sân bay", "Hành khách bay Singapore", "Khách dự hội nghị", "Tài xế giao hàng"], answer: 1 },
  { id: "p4-2", part: 4, skill: "listening", contextLabel: "Part 4 · Talk", prompt: "Nghe thông báo. Điều gì đã thay đổi?", transcript: "Attention passengers: Flight 318 to Singapore will depart from Gate 12, not Gate 8. Boarding begins at 6:40 p.m.", choices: ["Số hiệu chuyến bay", "Điểm đến", "Cổng khởi hành", "Giờ lên máy bay"], answer: 2 },
  { id: "p4-3", part: 4, skill: "listening", contextLabel: "Part 4 · Talk", prompt: "Nghe thông báo. Khi nào bắt đầu lên máy bay?", transcript: "Attention passengers: Flight 318 to Singapore will depart from Gate 12, not Gate 8. Boarding begins at 6:40 p.m.", choices: ["6:08 p.m.", "6:12 p.m.", "6:40 p.m.", "8:40 p.m."], answer: 2 },
  { id: "p5-1", part: 5, skill: "reading", contextLabel: "Part 5 · Incomplete Sentences", prompt: "The revised contract _____ by the legal team yesterday.", choices: ["review", "was reviewed", "has reviewing", "will review"], answer: 1 },
  { id: "p5-2", part: 5, skill: "reading", contextLabel: "Part 5 · Incomplete Sentences", prompt: "Ms. Park is responsible _____ arranging the vendor meeting.", choices: ["at", "for", "with", "from"], answer: 1 },
  { id: "p5-3", part: 5, skill: "reading", contextLabel: "Part 5 · Incomplete Sentences", prompt: "The new software works more _____ than the previous version.", choices: ["efficient", "efficiency", "efficiently", "efficientness"], answer: 2 },
  { id: "p6-1", part: 6, skill: "reading", contextLabel: "Part 6 · Text Completion", passage: "To: All Staff\nSubject: Building access\n\nThe main entrance will be closed on Saturday while the security system is _____. Please use the west entrance instead.", prompt: "Chọn từ phù hợp cho chỗ trống.", choices: ["upgraded", "upgrade", "upgrades", "upgrading"], answer: 0 },
  { id: "p6-2", part: 6, skill: "reading", contextLabel: "Part 6 · Text Completion", passage: "To: All Staff\nSubject: Building access\n\nThe main entrance will be closed on Saturday while the security system is being upgraded. Please use the west entrance _____.", prompt: "Chọn từ phù hợp cho chỗ trống.", choices: ["instead", "already", "rarely", "nearly"], answer: 0 },
  { id: "p6-3", part: 6, skill: "reading", contextLabel: "Part 6 · Text Completion", passage: "To: All Staff\nSubject: Building access\n\nThe main entrance will be closed on Saturday while the security system is being upgraded. Please use the west entrance instead.", prompt: "Mục đích của email là gì?", choices: ["Mời họp an ninh", "Thông báo thay đổi lối vào", "Tuyển nhân viên bảo vệ", "Yêu cầu đổi mật khẩu"], answer: 1 },
  { id: "p7-1", part: 7, skill: "reading", contextLabel: "Part 7 · Reading Comprehension", passage: "Dear Mr. Nguyen,\n\nThank you for your order of 50 desk lamps. The items will be delivered on May 14 between 9 a.m. and noon. If no one is available to receive the delivery, please contact us by May 10.\n\nSincerely,\nBright Office Supplies", prompt: "Khi nào đơn hàng sẽ được giao?", choices: ["Ngày 10 tháng 5", "Ngày 14 tháng 5", "Trước 9 giờ sáng", "Sau buổi trưa"], answer: 1 },
  { id: "p7-2", part: 7, skill: "reading", contextLabel: "Part 7 · Reading Comprehension", passage: "Dear Mr. Nguyen,\n\nThank you for your order of 50 desk lamps. The items will be delivered on May 14 between 9 a.m. and noon. If no one is available to receive the delivery, please contact us by May 10.\n\nSincerely,\nBright Office Supplies", prompt: "Người nhận cần làm gì nếu không có mặt?", choices: ["Hủy đơn hàng", "Gọi trước ngày 10 tháng 5", "Đến cửa hàng", "Thanh toán thêm phí"], answer: 1 },
  { id: "p7-3", part: 7, skill: "reading", contextLabel: "Part 7 · Reading Comprehension", passage: "Dear Mr. Nguyen,\n\nThank you for your order of 50 desk lamps. The items will be delivered on May 14 between 9 a.m. and noon. If no one is available to receive the delivery, please contact us by May 10.\n\nSincerely,\nBright Office Supplies", prompt: "Công ty Bright Office Supplies làm gì?", choices: ["Cung cấp đèn bàn", "Sửa máy tính", "Tổ chức vận chuyển quốc tế", "Cho thuê văn phòng"], answer: 0 },
];

export const mockPartNames = ["Photographs", "Question–Response", "Conversations", "Talks", "Incomplete Sentences", "Text Completion", "Reading Comprehension"] as const;
