import { Bar, BarChart, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { buildMockProgressData, type MockProgressAttempt } from "@shared/mockProgress";
import "./mock-progress-chart.css";

export function MockProgressChart({ attempts }: { attempts: MockProgressAttempt[] }) {
  const data = buildMockProgressData(attempts);
  const tooltip = (value: number, key: string): [string, string] => [key === "minutes" ? `${value} phút` : `${value}%`, key === "score" ? "Điểm thực hành" : key === "listening" ? "Listening" : key === "reading" ? "Reading" : "Thời gian"];
  return <section className="mock-progress panel"><div className="panel-title"><div><span className="eyebrow">TIẾN BỘ THI THỬ</span><h2>Điểm, kỹ năng và thời gian</h2></div><span className="soft-tag">{data.length} phiên gần đây</span></div>{data.length ? <div className="mock-chart-wrap"><div className="chart-legend"><span><i className="legend-score" />Tổng</span><span><i className="legend-listening" />Listening</span><span><i className="legend-reading" />Reading</span></div><ResponsiveContainer width="100%" height={220}><LineChart data={data} margin={{ top: 10, right: 12, left: -18, bottom: 4 }}><XAxis dataKey="attempt" tick={{ fontSize: 10 }} tickLine={false} axisLine={false} /><YAxis domain={[0, 100]} tick={{ fontSize: 10 }} tickLine={false} axisLine={false} /><Tooltip formatter={tooltip} labelFormatter={(_, payload) => payload[0]?.payload?.date ?? ""} contentStyle={{ borderRadius: 10, border: "1px solid #d8d8cf", fontSize: 11 }} /><Line type="monotone" dataKey="score" stroke="#c9623f" strokeWidth={3} dot={{ r: 4, fill: "#c9623f" }} /><Line type="monotone" dataKey="listening" stroke="#3c806b" strokeWidth={2} dot={false} /><Line type="monotone" dataKey="reading" stroke="#c69a30" strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer><div className="chart-time"><span>Thời gian làm bài (phút)</span><ResponsiveContainer width="100%" height={110}><BarChart data={data} margin={{ top: 4, right: 12, left: -18, bottom: 0 }}><XAxis dataKey="attempt" tick={{ fontSize: 10 }} tickLine={false} axisLine={false} /><YAxis tick={{ fontSize: 10 }} tickLine={false} axisLine={false} /><Tooltip formatter={tooltip} labelFormatter={(_, payload) => payload[0]?.payload?.date ?? ""} contentStyle={{ borderRadius: 10, border: "1px solid #d8d8cf", fontSize: 11 }} /><Bar dataKey="minutes" fill="#7b9f8a" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div><p><b>{data.at(-1)?.score}%</b> ở lần gần nhất · Listening {data.at(-1)?.listening}% · Reading {data.at(-1)?.reading}% · {data.at(-1)?.minutes} phút. Đây là độ chính xác phiên mô phỏng, không quy đổi thành điểm TOEIC chính thức.</p></div> : <div className="mock-chart-empty"><b>Chưa có phiên thi thử để vẽ biểu đồ.</b><span>Hoàn thành bài mô phỏng 200 câu đầu tiên để theo dõi xu hướng điểm, kỹ năng và thời gian.</span></div>}</section>;
}
